### ISSUE TITLE
Feedback on LDTemplates article

### ISSUE THREAD

**Issue by csarven** [AtomGraph/Linked-Data-Templates#1]
- "Ontology as a component ..." -- LDP doesn't mandate other than the minimal LDP vocabulary.
- "It is coupled with HTTP ..." -- Specify what makes RDF CRUD different or special handling.
- "In order to accommodate..." -- Why is this a bad thing? Not mandating gives some freedom of implementation. That could be a plus or a minus depending how one looks at it. It doesn't forbid SPARQL either.
- "It does not offer a ..." -- HTTP PUT/POST, GET, PATCH/POST, DELETE... OPTIONS? 
- "XSLT is a homoiconic ..." This is one level down implementation specific. What are the alternatives? Can this be abstracted?
- "PUT /people/Berners-Lee" -- How is PUT applied to :PersonDocument template?
- "is also very scalable" -- Provide benchmarks

**Comment by namedgraph** [comment]
@csarven thanks for your feedback!

The main problem with LDP is that it does not have an abstract model. The only RDF-related specification that does is SPARQL, which has an algebra. That is more important than freedom of implementation, in our opinion, and that is why we have developed an LDT algebra similar to SPARQL (yet to be made public).

Another problem is that there is no standard way to capture application-specific LDP behaviour. From our point of view, it is not desirable for _all_ Linked Data applications to use the same processing model. Rather, the processing should depend on an app-specific component (ontology), which should be available for interchange using standard means.

Homo-iconicity enables meta-programming, which was one of our goals.

`PUT` is an Update interaction, which means it generates a SPARQL update consisting of 2 parts: `DELETE` and `INSERT DATA`. The `DELETE` part is taken from `ldt:update` value and `(?this, <http://linkeddatahub.com/people/Berners-Lee>)` variable binding is applied. `INSERT DATA` is generated directly from `PUT` request body. The combined update request is then executed on the SPARQL service. Does this help?

**Comment by namedgraph** [comment]
@csarven @timbl @sandhawke would love your opinion on the LDT spec draft :)
https://atomgraph.github.io/Linked-Data-Templates/
